# Tagged releases of Python docker images can be found at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9


before_script:
  - python --version  # Print out python version for debugging
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - Test


pytest:
  stage: Test
  script:
  - python -m pytest --html=test_cases_report.html tests/


coverage:
  stage: Test
  allow_failure: true
  script:
  - python -m pytest --cov --cov-report=html  tests/

